language: cpp
env:
  global:
    - email=imagire@gmail.com
    - username=imagire
    - secure: "v6t6pKfdiURPf2N2oxB8N2lfrJnS9nkvVK3Bf2+bCIE2ZP1fdQ96ASZ5x/3BRAJeTeFqNsoXvl/tz0Sjn7N73ruqc9W63jjU3S4H0x0u/3WjfgH8Ue52zDJAjEHFSz6D4bBEaImmW/gs9fy4oI376hMCNtJFN3MvWPkTruoWqPRexGHKhZFJH0mJfO/0LgX+qbHzRG5mwvR7BBQxzGoHxGMB6vAct+YrVLECkcREggGv2wh5/h1UiQBgyPzBZQWafU7NVa98V4iCguD+SeiHGTZcWCsoSwx/G2WPgrtMbrEnQf2Z/1CiMiOf1eDfxraYxPaPd+JEfYO8VyNWsMOtXTzngHGQZmwmpZ2ZeHO2ft/z5BNr9K2JXnUicf3gCLa6J88iCNiM26r+7UI6ZTagbY/o/oQPm5EIqp6eiZclBcY0Jo58vI9SeQ36+MRu5mmWtHrIl4fpKQXqQLaHCEUOf8/xrWXU8Pdi2LzQKHKD44rM3/zPWdJtd7nYn7i1eS2tKAOyDZ5i121vd0MoqaeGzxYkSF4qhis/GYYDR40Q/5kCYldw+pSUMuwW+ut5gAJozn/b45yWxTw2SUuJpceVNO0cu3X1hHh9qJbw07j/EXw/5mu2QdqM59DQng0soNoKUA9DELfXPH0rxenR7oujfBFekr6MKZfaEElATsfwLdU="
script:
  - g++ --version
  - cd src
  - mkdir bin
  - make clean
  - make depend
  - make
  - ls -lsaR
  - cd bin
  - ./a.out
after_success:
#  - echo $TRAVIS_PULL_REQUEST
#  - echo $TRAVIS_BRANCH
  - test "$TRAVIS_BRANCH" != "master" && exit 1
  - test "$TRAVIS_PULL_REQUEST" = "true" && exit 1
  - cp ../../static/* .
  - git config --global user.email "$email"
  - git config --global user.name "$username"
  - rm -rf .git
  - git init
  - git add --all
  - git commit -m "deploy commit from travis"
  - git push -f https://${GH_TOKEN}@github.com/imagirelab/rtc5.git master
  
